---
commitizen:
  annotated_tag: true
  changelog_file: CHANGELOG.md
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 0.2.0-dev.3
  version_files:
  - VERSION
  version_scheme: semver2
