repos:
- hooks:
  - args:
    - -c
    - Digital Holography Foundation
    files: \.(cc|cu|hh|hxx|cuh|cuhxx|py|txt|cmake|json)$
    id: addlicense
  repo: https://github.com/google/addlicense
  rev: v1.2.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.10.0
