repos:
  # -------------------------------------------------------------------
  # Add license headers
  # -------------------------------------------------------------------
  - repo: https://github.com/google/addlicense
    rev: v1.2.0
    hooks:
      - id: addlicense
        name: addlicense
        args:
          - -c
          - "Digital Holography Foundation"
        files: \.(cc|hh|cu|cuh|hxx|cuhxx|py|txt|cmake|json)$
        stages: [ pre-commit ]

  # -------------------------------------------------------------------
  # Check C++ / CUDA formatting
  # -------------------------------------------------------------------
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        files: \.(cc|hh|cu|cuh|hxx|cuhxx)$
        args:
          - --style=file
          - --dry-run
          - --Werror
        stages: [ pre-commit ]