site_name: Holoflow
nav:
  - Home: index.md
  - About: about.md

  - Holovibes: 
    - Overview: holovibes/index.md
    - Tasks:
      - Sources:
        - Ametek s710 Euresys Coaxlink Octo: holovibes/tasks/sources/ametek_s710_euresys_coaxlink_octo.md
        - Ametek s711 Euresys Coaxlink QSFP+: holovibes/tasks/sources/ametek_s711_euresys_coaxlink_qsfp+.md
        - Holofile: holovibes/tasks/sources/holofile.md
      - Sinks:
        - Display Tensor: holovibes/tasks/sinks/display_tensor.md
        - Holofile: holovibes/tasks/sinks/holofile.md
      - Synchronous:
        - Angular Spectrum: holovibes/tasks/syncs/angular_spectrum.md
        - Average: holovibes/tasks/syncs/average.md
        - Conversion: holovibes/tasks/syncs/conversion.md
        - Convolution: holovibes/tasks/syncs/convolution.md
        - FFT Shift: holovibes/tasks/syncs/fft_shift.md
        - Filter 2D: holovibes/tasks/syncs/filter2d.md
        - Fresnel Diffraction: holovibes/tasks/syncs/fresnel_diffraction.md
        - Memcpy: holovibes/tasks/syncs/memcpy.md
        - PCA: holovibes/tasks/syncs/pca.md
        - Percentile Clip: holovibes/tasks/syncs/pct_clip.md
        - Registration: holovibes/tasks/syncs/registration.md
        - Reshape: holovibes/tasks/syncs/reshape.md
        - Rotation: holovibes/tasks/syncs/rotation.md
        - STFT: holovibes/tasks/syncs/stft.md
      - Asynchronous:
        - Batch Queue: holovibes/tasks/asyncs/batch_queue.md
        - Sliding Average: holovibes/tasks/asyncs/sliding_average.md

  - Holoflow:
    - Overview: holoflow/index.md
    - Concepts:
      - Graph Model: holoflow/concepts/graph.md
      - Tasks: holoflow/concepts/tasks.md
  - Curaii: curaii/index.md
  - Holofile: holofile/index.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      check_paths: true
  - attr_list

plugins:
  - search
  - mermaid2

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

use_directory_urls: false
