site_name: Holoflow
nav:
  - Home: index.md
  - About: about.md

  - Holovibes: 
    - Overview: holovibes/index.md
    - Tasks:
      - Sources:
        - Holofile:
          - Settings: schemas/holofile_settings.md
      - Sinks:
        - Display Tensor:
          - Settings: schemas/display_tensor_settings.md
      - Synchronous:
        - Angular Spectrum:
          - Settings: schemas/angular_spectrum_settings.md
        - Average:
          - Settings: schemas/average_settings.md
        - Conversion:
          - Settings: schemas/conversion_settings.md
        - Convolution:
          - Settings: schemas/convolution_settings.md
        - FFT Shift:
          - Settings: schemas/fft_shift_settings.md
        - Memcpy:
          - Settings: schemas/memcpy_settings.md
        - PCA:
          - Settings: schemas/pca_settings.md
        - Percentile Clip:
          - Settings: schemas/pct_clip_settings.md
        - Reshape:
          - Settings: schemas/reshape_settings.md
        - STFT:
          - Settings: schemas/stft_settings.md
        - Fresnel Diffraction:
          - Settings: schemas/fresnel_diffraction_settings.md
      - Asynchronous:
        - Batch Queue:
          - Settings: schemas/batch_queue_settings.md
        - Sliding Average:
          - Settings: schemas/sliding_average_settings.md

  - Holoflow:
    - Overview: holoflow/index.md
    - Concepts:
      - Graph Model: holoflow/concepts/graph.md
      - Tasks: holoflow/concepts/tasks.md
  - Curaii: curaii/index.md
  - Holofile: holofile/index.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list

plugins:
  - search
  - mermaid2

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
