name: Build Package

on:
  push:
    branches: [ refactor ]

  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [ self-hosted, windows, x64 ]
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

      uses: actions/download-artifact@v4
      with:
        name: fc-cache
        path: .fc
      continue-on-error: true
        
    - name: Configure
      run: |
        cmake --preset msvc-multi -DFETCHCONTENT_BASE_DIR="C:/.fc"
          
    - name: Build
      run: |
        cmake --build --preset build-Release -j

    - name: Test
      run: |
        build\msvc-multi\Release\holoflow_test.exe
        