name: Deploy Documentation

on:
  push:
    branches: [ refactor ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-fork:
    runs-on: [ self-hosted, windows, x64 ]
    steps:
      - name: Fork Check
        if: github.event.pull_request.head.repo.fork == true
        run: |
          echo "This is a forked repository."
          exit 1

  documentation:
    runs-on: [ self-hosted, windows, x64 ]
    needs: check-fork

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m venv .env
          .\.env\Scripts\activate
          pip install mkdocs mkdocs-material mkdocs-material-extensions

      - name: Deploy MkDocs
        run: |
          .\.env\Scripts\activate
          cd doc/mkdocs
          mkdocs gh-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up
        run: |
          deactivate
          Remove-Item .env -Recurse -Force
