name: Release CI

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  check-fork:
    runs-on: [ self-hosted, windows, x64 ]
    steps:
      - name: Fork Check
        if: github.event.pull_request.head.repo.fork == true
        run: |
          echo "This is a forked repository."
          exit 1

  build-package:
    runs-on: [ self-hosted, windows, x64 ]
    needs: check-fork    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: |
          cmake --preset msvc-multi -DFETCHCONTENT_BASE_DIR="C:/.fc"
            
      - name: Build
        run: |
          cmake --build --preset build-Release -j

      - name: Test
        run: |
          build\msvc-multi\Release\holoflow_test.exe
        
      - name: Package
        run: |
          cmake --build --preset build-Release --target package -j

      - name: Create Release
        run: |
          $version = Get-Content VERSION
          gh release create "v$version" "build/msvc-multi/Holoflow-$version-win64.exe" `
            --title "v$version" `
            --notes "Automated release of version $version" `
            --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}